### PR TITLE
Check for device status before sending a control command

### LINKED ISSUE #4: warn if using a control command when deck is not in remote
The deck will report if in local or remote mode in the first byte of the status:

```
$ sony9pin 8 0
Info: open device cu.usbserial-AB0L8UIT.
Info: open device OK.
Info: get device status.
<Remote Status>
==================
------byte 0------
Cassette Out :  0
Servo Ref Mis:  0
Local        :  1
```

If the deck is in local or remote mode, the stdout is the same though in one the command doesn't do anything:

```
$ sony9pin 8 p
Info: open device cu.usbserial-AB0L8UIT.
Info: open device OK.
Info: play.
```

I suggest that for the control commands (eject, ff, rew, stop, play) that if `local=1` then warn "The device is in local mode. Please switch to remote and try again."

Relatedly if there is no cassette in the deck, the control commands won't work.

```
$ sony9pin 8 0
Info: open device cu.usbserial-AB0L8UIT.
Info: open device OK.
Info: get device status.
<Remote Status>
==================
------byte 0------
Cassette Out :  1
Servo Ref Mis:  0
Local        :  1
```

So if `cassette_out=1` then I suggest to warn "The device does not contain a cassette. Please insert media and try again."

cc @libbyhopfauf for advice on wording.

### PR DESCRIPTION
**Pull request by g-maxime**
Fixes #4 

Please test

Signed-off-by: Maxime Gervais <gervais.maxime@gmail.com>

### CODE REVIEW

**Comment by dericed** [comment]
This works well, but I have a few comments.

If I have the tape in and tape playing and the deck is in local mode, I can run a status call like this:

```
$ sony9pin 8 0
<Remote Status>
==================
------byte 0------
Cassette Out :  0
Servo Ref Mis:  1
Local        :  1
------byte 1------
Standby      :  1
Stop         :  0
Eject        :  0
Rewind       :  0
Forward      :  0
Record       :  0
Play         :  1
------byte 2------
Servo Lock   :  1
TSO Mode     :  0
Shuttle      :  0
Jog          :  0
Var          :  0
Direction    :  0
Still        :  0
Cue Up       :  0
------byte 3------
Auto Mode    :  0
Freeze On    :  0
CF Mode      :  0
Audio Out Set:  0
Audio In Set :  0
Out Set      :  0
In Set       :  0
------byte 4------
Select EE    :  0
Full EE      :  0
Edit         :  0
Review       :  0
Auto Edit    :  0
Preview      :  0
Preroll      :  0
------byte 5------
Insert       :  0
Assemble     :  0
Video        :  0
A4           :  0
A3           :  0
A2           :  0
A1           :  0
------byte 6------
Lamp Still   :  0
Lamp Fwd     :  1
Lamp Rev     :  0
SRCH Led 8   :  0
SRCH Led 4   :  0
SRCH Led 2   :  0
SRCH Led 1   :  0
------byte 7------
AUD Split    :  0
Sync Act     :  0
Spot Erase   :  0
In Out       :  0
------byte 8------
Buzzer       :  0
Lost Lock    :  0
Near EOT     :  0
EOT          :  0
CF Lock      :  0
SVO Alarm    :  0
Sys Alarm    :  0
Rec Inhibit  :  0
------byte 9------
FNC Abort    :  0
==================
Error: remote control is disabled.
Info: stop deck.
```

Since I didn't make a call to control the deck (stop, play, etc) but only to ask the status, I think "Error" in "Error: remote control is disabled." is too strong. I suggest "Info:" here.

I'm not sure what "Info: stop deck." is saying here. I did not send a stop command and the deck is playing when I run the command (as byte 1 says).

**Comment by g-maxime** [comment]
A status command can stop the deck:
https://github.com/mipops/digividcommander/blob/main/tools/sony9pin/sony9pin.cpp#L146
idk why this code is here.

Can also cause #13  if is_stopping() return incosistant values.

**Comment by JeromeMartinez** [comment]
> idk why this code is here.

Maybe a mistake on my side, let's remove that.

**Comment by dericed** [comment]
works for me thx :D

**Pull request merged**
